# Generated by Django 4.0.5 on 2022-07-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component', '0002_resources_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(max_length=20)),
                ('number_of_members', models.IntegerField()),
            ],
        ),
    ]
